# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(0, 'Added'), (1, 'InProgress'), (2, 'Delivered'), (3, 'CLOSED')], default=0)),
                ('last_status', models.IntegerField(choices=[(0, 'Added'), (1, 'InProgress'), (2, 'Delivered'), (3, 'CLOSED')], default=0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('target_date', models.DateField()),
                ('product', models.IntegerField(choices=[(1, 'Policies'), (2, 'Billing'), (3, 'Claims'), (4, 'Reports')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feature', to='features.Client')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='TargetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'TargetVersion',
                'verbose_name_plural': 'TargetVersions',
            },
        ),
    ]
